algoritmo "semnome"
// Função :
// Autor :
// Data : 28/06/2022
// Seção de Declarações 
var
numero: caracter
convertido: inteiro
comprimento: inteiro

inicio
escreval("Digite um número: ")
leia(numero)
convertido <- asc(numero)
comprimento <- compr(numero)


escreval("O número digitado é: ", convertido)
escreval("Comprimento numero digitado é: ",comprimento)

// Seção de Comandos 
fimalgoritmo
